### ISSUE TITLE
Merge example request body schemas into the body schema generated from the request itself.

### ISSUE THREAD

**Issue by kevinswiber** [kevinswiber/postman2openapi#22]

**Comment by mjg257212** [comment]
Hi Kevin,

I am uncertain if this question is related to this ticket, but I thought that I'd ask.

I had the good fortune of meeting with Francisco Deppe of the Postman team about a month ago.
Since that time I have been using Postman and the postman2openapi tool that Francisco recommended to generate the OAS Definition file and that has been great.

I was wondering about what gets included in the definition file.  
It seems that once I have a collection, I can generate a web-view of the API as shown below using the View in web button.

That view is cool in that it contains an example request and response.

My question is as follows:

**Is there a way of getting that into the YAML created by postman2openapi?**

**Comment by kevinswiber** [comment]
Related but not exactly a duplicate: #29.

**Comment by kevinswiber** [comment]
Fixed in #56.
